services:
  - type: web
    name: ben-url-filter-bot
    env: python
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    startCommand: python3 bot.py
    buildCommand: |
      apt-get update && apt-get install -y python3-dev build-essential
      pip3 install -U pip setuptools wheel
      pip3 install -U -r requirements.txt --prefer-binary
    repo: https://github.com/itzmeproman/Teenfire.git
    healthCheckPath: /

    envVars:
      - key: ENV_VAR_KEY
        value: ENV_VAR_VALUE
      # Add your environment variables here
